import re
from playwright.sync_api import Playwright, sync_playwright


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://127.0.0.1:8000/")
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Anmelden").click()
    page.get_by_role("textbox", name="User name").click()
    page.get_by_role("textbox", name="User name").fill("john")
    page.get_by_role("textbox", name="User name").press("Tab")
    page.get_by_role("textbox", name="Password").fill("johnpassword")
    page.get_by_role("button", name="Anmelden").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Einkaufsliste").click()
    page.get_by_role("link").nth(2).click()
    page.get_by_role("textbox", name="My awesome list").click()
    page.get_by_role("textbox", name="My awesome list").fill("Birthday")
    page.get_by_role("textbox", name="My awesome list").press("Tab")
    page.locator('input[name="purchase_date"]').fill("2026-01-01")
    page.get_by_role("button", name="Speichern").click()
    page.get_by_role("textbox").first.click()
    page.get_by_role("textbox").fill("Cake")
    page.get_by_role("spinbutton").click()
    page.get_by_role("spinbutton").fill("2")
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.get_by_role("textbox").nth(1).click()
    page.get_by_role("textbox").nth(1).fill("Tea")
    page.get_by_role("spinbutton").nth(1).click()
    page.get_by_role("spinbutton").nth(1).fill("1")
    page.get_by_role("button").nth(3).click()
    page.get_by_role("link", name="Einkaufsliste").click()
    page.get_by_role("link", name="Birthday").click()
    page.get_by_role("link", name="Einkaufsliste").click()
    page.get_by_role("link").nth(4).click()
    page.get_by_role("button").nth(3).click()
    page.get_by_role("link", name="Einkaufsliste").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Gerichte").click()
    page.get_by_role("main").get_by_role("link").click()
    page.get_by_role("textbox", name="My awesome meal").click()
    page.get_by_role("textbox", name="My awesome meal").fill("Pizza")
    page.get_by_role("combobox").select_option("full")
    page.get_by_role("button", name="Speichern").click()
    page.get_by_role("link").first.click()
    page.get_by_text("Pizza").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Einkaufsliste").click()
    page.get_by_role("link", name="Birthday").first.click()
    page.get_by_role("button", name="Löschen").click()
    page.get_by_role("link", name="Löschen").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Gerichte").click()
    page.get_by_role("link", name="Pizza").click()
    page.get_by_role("button", name="Löschen").click()
    page.get_by_role("link", name="Löschen").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Abmelden").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
