
POST http://127.0.0.1:4000/v1/accounts/users HTTP/1.1
Content-Type: application/json
Authorization: ZWQ1ZmE5ZmEtZmI0NS00YjJiLWJhMDQtY2YwNjQ0ODcwNzQ0

{
    "user": {
        "name": " Bob",
        "email": "bob2@test.xyz",
        "password": "THIS_15_password"
    }
}

###

GET http://127.0.0.1:4000/v1/accounts/users/1 HTTP/1.1

###

PUT http://127.0.0.1:4000/v1/accounts/users/1 HTTP/1.1
content-type: application/json

{
    "user": {
        "name": "Alice"
    }
}

###

DELETE  http://127.0.0.1:4000/v1/accounts/users/1 HTTP/1.1

###

POST http://127.0.0.1:4000/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "bob@test.xyz",
    "password": "THIS_15_password"
}


###

GET http://127.0.0.1:4000/auth/signout HTTP/1.1
Cookie: Idea-fd497060=b8dd64bf-69dc-422a-b191-dacd09bbf275; Idea-652a9d3f=4bdca5ae-9569-4397-b73a-307012e14a98; _ga=GA1.1.2025059052.1566145433; _jarvis_key=SFMyNTY.g3QAAAABbQAAAAd1c2VyX2lkYQE.ASP9yuhrQaCia604x5TioCKPvteoqlxJMC976cuWMuc
