# Generated by Django 5.0.6 on 2024-06-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMPLETE", "Complete"),
                            ("MAIN", "Main"),
                            ("SUPPLEMENT", "Supplement"),
                        ],
                        default="COMPLETE",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
