
version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-}
      POSTGRES_DB: jarvis_dev
    networks:
      - jarvis_network

networks:
  jarvis_network:

volumes:
  db-data:
