### LOGIN
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "email": "corka149@mailbox.org",
  "password": "password"
}

### LOGOUT
POST http://localhost:8080/v1/auth/logout

### CHECK AUTH
HEAD http://localhost:8080/v1/auth/check

### GET ALL
GET http://localhost:8080/v1/lists

### GET ONE
GET http://localhost:8080/v1/lists/634c705e193c67cbb579395c


### CREATE
POST http://localhost:8080/v1/lists
Content-Type: application/json

{
  "no": 1,
  "reason": "holiday",
  "occurs_at": 1664194915,
  "done": false,
  "products": [
    {
      "name": "bread",
      "amount": 1
    },
    {
      "name": "apples",
      "amount": 42
    }
  ]
}

### DELETE
DELETE http://localhost:8080/v1/lists/6418be4a0af144d1eb5bbbd5

### UPDATE
PUT http://localhost:8080/v1/lists/63505ceeb7dac520fafd9ad9
Content-Type: application/json

{
  "no": 1,
  "reason": "holiday",
  "occurs_at": 1664194915,
  "done": true,
  "products": [
    {
      "name": "beer",
      "amount": 22
    },
    {
      "name": "butter",
      "amount": 3
    }
  ]
}
