### LOGIN
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "email": "corka149@mailbox.org",
  "password": "password"
}

### LOGOUT
POST http://localhost:8080/v1/auth/logout

### GET ALL
GET http://localhost:8080/v1/lists

### GET ONE
GET http://localhost:8080/v1/lists/633a70926c00a3708d74fe5d


### CREATE
POST http://localhost:8080/v1/lists
Content-Type: application/json

{
  "no": 1,
  "reason": "birthday",
  "occurs_at": {
    "$date": {
      "$numberLong": "1664194915000"
    }
  },
  "done": false,
  "products": [
    {
      "name": "bread",
      "amount": 1
    },
    {
      "name": "apples",
      "amount": 42
    }
  ]
}

### DELETE
DELETE http://localhost:8080/v1/lists/6334a2ef4740b23e3ed6cb71

### UPDATE
PUT http://localhost:8080/v1/lists/633a7046c9797d3aab817596
Content-Type: application/json

{
  "no": 1,
  "reason": "holiday",
  "occurs_at": {
    "$date": {
      "$numberLong": "1664194915000"
    }
  },
  "done": true,
  "products": [
    {
      "name": "bread",
      "amount": 1
    },
    {
      "name": "water",
      "amount": 42
    }
  ]
}
