[package]
name = "jarvis-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-session = { version = "0.7", features = ["cookie-session"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
futures-util = "0.3"
mongodb = "2.3.0"
futures = "0.3.24"
log = "0.4"
env_logger = "0.9"

[dependencies.uuid]
version = "1.1.2"
features = [
    # Lets you generate random UUIDs
    "v4",
    # Use a faster (but still sufficiently random) RNG
    "fast-rng",
    # Enable better diagnostics for compile-time UUIDs
    "macro-diagnostics",
]
