version: 3

tasks:
  generate:
    desc: Generate all code
    cmds:
      - sqlc generate
      - templ generate
      - tailwindcss -i ./static/css/input.css -o ./static/css/styles.css

  release:
    desc: Release
    cmds:
      - docker build -t corka149/jarvis:6.0.1 .
      - docker push corka149/jarvis:6.0.1
