version: 3

tasks:
  generate:
    desc: Generate all code
    cmds:
      - sqlc generate
      - templ generate

  setup:
    desc: Install dependencies
    cmds:
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/air-verse/air@latest
