logging:
  level: debug

database:
  connection: mongodb://myadmin:mypassword@localhost:27017

security:
  secret_key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

static_file_dir: /tmp
