# Generated by Django 6.0.2 on 2026-02-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(verbose_name='Purchase date')),
                ('done', models.BooleanField(verbose_name='Done')),
                ('deleted', models.BooleanField(verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppinglist')),
            ],
        ),
    ]
