# Generated by Django 6.0.2 on 2026-03-09 20:08

import shopping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[(shopping.models.MealCategory['MAIN'], 'Main'), (shopping.models.MealCategory['GARNISH'], 'Garnish'), (shopping.models.MealCategory['FULL'], 'Full')])),
            ],
        ),
    ]
