# Generated by Django 6.0.2 on 2026-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collected',
            field=models.BooleanField(default=True, verbose_name='Collected'),
        ),
    ]
