"""
Django settings for web_jarvis project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

IS_PRODUCTION = os.getenv("ENVIRONMENT") == "PRODUCTION"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ej)pa1p)a^!1(kc&zpcrg9+hxh6j+)1g_(wxmnffv!fyv%pbb_"

ALLOWED_HOSTS = []

if IS_PRODUCTION:
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_PRELOAD = True
    SECRET_KEY = os.getenv("SECRET_KEY")
    SESSION_COOKIE_SECURE = True
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(",")
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # Load balance will take care
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

# Application definition

INSTALLED_APPS = [
    "daphne",
    "pwa",
    "shopping.apps.ShoppingConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "web_jarvis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "web_jarvis.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DATABASE_NAME") or "jarvis_dev",
        "USER": os.getenv("DATABASE_USER") or "db_admin",
        "PASSWORD": os.getenv("DATABASE_PASSWORD") or "a_secret",
        "HOST": os.getenv("DATABASE_HOST") or "localhost",
        "PORT": os.getenv("DATABASE_PORT") or "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_URL = "/shopping/login"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "de"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "assets")

# Daphne
ASGI_APPLICATION = "web_jarvis.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_HOST") or "redis://127.0.0.1:6379"],
        },
    },
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# PWA
PWA_APP_DEBUG_MODE = not IS_PRODUCTION
PWA_APP_NAME = "Jarvis"
PWA_APP_DESCRIPTION = "Your personal management app"
PWA_APP_THEME_COLOR = "#1976d2"
PWA_APP_BACKGROUND_COLOR = "#fafafa"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_START_URL = "/"
PWA_APP_ICONS = [
    {
        "src": "/static/images/icon-48x48.png",
        "sizes": "48x48",
    },
    {
        "src": "/static/images/icon-72x72.png",
        "sizes": "72x72",
    },
    {
        "src": "/static/images/icon-96x96.png",
        "sizes": "96x96",
    },
    {
        "src": "/static/images/icon-144x144.png",
        "sizes": "144x144",
    },
    {
        "src": "/static/images/icon-192x192.png",
        "sizes": "192x192",
    },
    {
        "src": "/static/images/icon-512x512.png",
        "sizes": "512x512",
    },
]
PWA_APP_ICONS_APPLE = [
    {
        "src": "/static/images/icon-48x48.png",
        "sizes": "48x48",
    },
    {
        "src": "/static/images/icon-72x72.png",
        "sizes": "72x72",
    },
    {
        "src": "/static/images/icon-96x96.png",
        "sizes": "96x96",
    },
    {
        "src": "/static/images/icon-144x144.png",
        "sizes": "144x144",
    },
    {
        "src": "/static/images/icon-192x192.png",
        "sizes": "192x192",
    },
    {
        "src": "/static/images/icon-512x512.png",
        "sizes": "512x512",
    },
]
PWA_APP_SPLASH_SCREEN = [
    {
        "src": "/static/images/icon-512x512.png",
        "media": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)",
    }
]
PWA_APP_DIR = "ltr"
PWA_APP_LANG = "de"
