name: Elixir CI

on: push

jobs:
  test:
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: jarvis_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        otp-version: 23.x
        elixir-version: 1.11.x
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test

  analyze:
    runs-on: ubuntu-latest
    name: Dialyzer - OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 23.x
          elixir-version: 1.11.x
      - run: mix deps.get
      - run: mix dialyzer
      - run: mix credo --strict
      