name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v3
    - name: Build
      run:  |
          cd jarvis-backend
          cargo build --verbose
    - name: Run tests
      run:  |
          cd jarvis-backend
          cargo test --verbose
    - name: Run linter
      run:  |
          cd jarvis-backend
          cargo clippy
    - name: Run format-check
      run:  |
          cd jarvis-backend
          rustfmt --check --edition 2021 ./src/*
